"""add_indexes

Revision ID: 9201c09c54c1
Revises: 0a8557cb58b0
Create Date: 2026-05-08 13:26:55.449631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9201c09c54c1'
down_revision: Union[str, Sequence[str], None] = '0a8557cb58b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_category_difficulty', 'tasks', ['category_id', 'difficulty'], unique=False)
    op.create_index('ix_tasks_elo_rating', 'tasks', ['elo_rating'], unique=False)
    op.create_index('ix_tasks_is_active', 'tasks', ['is_active'], unique=False)
    op.create_index('ix_users_elo_rating', 'users', ['elo_rating'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_elo_rating', table_name='users')
    op.drop_index('ix_tasks_is_active', table_name='tasks')
    op.drop_index('ix_tasks_elo_rating', table_name='tasks')
    op.drop_index('ix_tasks_category_difficulty', table_name='tasks')
    # ### end Alembic commands ###
